In [1]:
import pandas as pd
import numbers as np

In [2]:
url='https://storage.googleapis.com/kagglesdsdata/datasets/5266074/8764321/Domestic%20violence.csv?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gcp-kaggle-com%40kaggle-161607.iam.gserviceaccount.com%2F20241127%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20241127T134259Z&X-Goog-Expires=259200&X-Goog-SignedHeaders=host&X-Goog-Signature=2c991927a52dc0fc198c68a4aefde4bc6793ffc5ddeb8f43df939c629882efe276faed28f6551e05b4ea12e328126ff9184630dfbdaa4837a56fe0d36a8d9d5ce9b1756ca93c4cb5a6505c5ec51aef006ca9298b501312d487360e8b23528e2af17d8f60b88b8174d796f8cb56534d91fd770062731743032c32bda4b363379e6d44d43ef3cbe5f11c1e61f0d3a37e00d5086dd49cb3a85f4cd9aea39476f48d47b280c42609f64736ddb9b1b8da3400a720f9a8adb2209112bfc5c194f5c1c944bb9b65851c02263210fd197f9061fc4fc39698d5dfe7dd1af03b06f4b5f86e9f1e8354f99ad2a499819d02e58e06eaba25e1dc74fb905e7055807a318e3e2f'

In [5]:
vio=pd.read_csv(url)
vio.head(60)

    SL. No  Age Education  Employment   Income Marital status  Violence
0        1   30  secondary  unemployed       0         married       yes
1        2   47   tertiary  unemployed       0         married        no
2        3   24   tertiary  unemployed       0        unmarred        no
3        4   22   tertiary  unemployed       0        unmarred        no
4        5   50    primary  unemployed       0         married       yes
5        6   21   tertiary  unemployed       0        unmarred       yes
6        7   30   tertiary  unemployed       0         married        no
7        8   27   tertiary  unemployed       0         married        no
8        9   20   tertiary  unemployed       0        unmarred        no
9       10   18  secondary  unemployed       0         married        no
10      11   40    primary  unemployed       0         married        no
11      12   45    primary  unemployed       0         married       yes
12      13   45       none  unemployed       0         married        no
13      14   40       none  unemployed       0         married       yes
14      15   50    primary  unemployed       0         married       yes
15      16   43    primary  unemployed       0         married        no
16      17   18  secondary  unemployed       0        unmarred        no
17      18   15  secondary  unemployed       0        unmarred        no
18      19   44    primary  unemployed       0         married        no
19      20   35  secondary  unemployed       0         married        no
20      21   40    primary  unemployed       0         married        no
21      22   50       none  unemployed       0         married       yes
22      23   40   tertiary  unemployed       0         married       yes
23      24   35       none  unemployed       0         married       yes
24      25   44    primary  unemployed       0         married        no
25      26   23  secondary  unemployed       0         married       yes
26      27   24    primary  unemployed       0         married       yes
27      28   19  secondary  unemployed       0        unmarred        no
28      29   27  secondary  unemployed       0         married        no
29      30   20  secondary  unemployed       0         married        no
30      31   18  secondary  unemployed       0         married        no
31      32   23  secondary  unemployed       0         married        no
32      33   19  secondary  unemployed       0         married        no
33      34   19  secondary  unemployed       0         married        no
34      35   50    primary  unemployed       0         married       yes
35      36   25  secondary  unemployed       0         married        no
36      37   19  secondary  unemployed       0        unmarred        no
37      38   30    primary  unemployed       0         married       yes
38      39   24    primary  unemployed       0         married        no
39      40   23   tertiary  unemployed       0        unmarred        no
40      41   20  secondary  unemployed       0        unmarred        no
41      42   50       none  unemployed       0         married       yes
42      43   21  secondary  unemployed       0        unmarred        no
43      44   32   tertiary  unemployed       0        unmarred        no
44      45   30   tertiary  unemployed       0        unmarred        no
45      46   25  secondary  unemployed       0         married        no
46      47   26  secondary  unemployed       0         married       yes
47      48   40    primary  unemployed       0         married       yes
48      49   50    primary  unemployed       0         married       yes
49      50   43       none  unemployed       0         married       yes
50      51   35   tertiary  unemployed       0         married       yes
51      52   40    primary  unemployed       0         married       yes
52      53   40  secondary  unemployed       0         married       yes
53      54   25  secondary  unemployed       0         married        no
54      55   23  secondary  unemployed       0         married        no
55      56   37   tertiary  unemployed       0         married       yes
56      57   33    primary  unemployed       0         married       yes
57      58   23  secondary  unemployed       0         married        no
58      59   42       none  unemployed       0         married       yes
59      60   33    primary  unemployed       0         married       yes

In [6]:
vio.info

<bound method DataFrame.info of      SL. No  Age Education     Employment   Income Marital status  Violence
0         1   30  secondary     unemployed       0         married       yes
1         2   47   tertiary     unemployed       0         married        no
2         3   24   tertiary     unemployed       0        unmarred        no
3         4   22   tertiary     unemployed       0        unmarred        no
4         5   50    primary     unemployed       0         married       yes
..      ...  ...        ...            ...     ...             ...       ...
342     343   27   tertiary  semi employed   30000        unmarred        no
343     344   26   tertiary       employed   35000         married        no
344     345   27    primary     unemployed       0         married       yes
345     346   29    primary     unemployed       0         married        no
346     347   24  secondary     unemployed       0         married        no

[347 rows x 7 columns]>

In [7]:
vio.columns

Index(['SL. No', 'Age', 'Education ', 'Employment ', 'Income',
       'Marital status ', 'Violence '],
      dtype='object')

In [8]:
vio.index

RangeIndex(start=0, stop=347, step=1)

descripción
Este conjunto de datos contiene información sobre la violencia doméstica contra las mujeres en una zona rural específica de un país en desarrollo. Los datos se recopilan para ayudar a comprender la correlación entre varios factores socioeconómicos y la violencia doméstica.

Contenido del conjunto de datos
El conjunto de datos incluye las siguientes columnas:

SL. No: Número de serie del registro.
Edad: Edad del encuestado.
Educación: Nivel educativo del encuestado (terciario para secundario superior).
Empleo: Situación laboral del demandado.
Ingresos: Nivel de ingresos del encuestado (0 que indica que no hay ingresos).
Estado civil: Estado civil del demandado (casado o no casado).
Violencia: Indica si el encuestado ha sufrido violencia doméstica (sí o no).
Contexto
La violencia doméstica contra las mujeres es un problema importante en muchos países en desarrollo. Comprender los factores que contribuyen a esta violencia puede ayudar a crear intervenciones y políticas efectivas. Este conjunto de datos tiene como objetivo proporcionar una base para el análisis y la investigación en esta área crítica.
Inspiración
El conjunto de datos se puede utilizar para:

Analizar la correlación entre el nivel de educación y la violencia doméstica.
Estudie el impacto del estado civil en la violencia doméstica.
Explore la distribución por edades de las víctimas de violencia doméstica.
Identificar los posibles factores socioeconómicos que contribuyen a la violencia doméstica.

In [9]:
vio.dtypes

SL. No              int64
Age                 int64
Education          object
Employment         object
Income              int64
Marital status     object
Violence           object
dtype: object